version: '3.8'
services:
  v-blog:
    container_name: v-blog
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    networks:
      - common
    environment:
      PORT: 4000
      DATABASE_URL: "postgres://postgres:aioshima@postgres:5432/example?schema=public"
      NODE_ENV: 'development'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aioshima
      - POSTGRES_DB=example
    networks:
      - common
  
  pg-admin:
    container_name: pg_admin
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASS}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    depends_on:
      - postgres
    networks:
      - common
networks:
  common: